version: "3"

services:
  ####################### Database #######################
  database:
    restart: always
    container_name: dmft_api_db
    build:
      context: database/mongo
    env_file:
      - database/mongo/.env
    ports:
      - 27017:27017
    volumes:
      - database-data:/data/db
    networks:
      - dmft_network

  ####################### Backend #######################
  api:
    restart: always
    container_name: dmft_api
    build:
      context: api/dotnet
    env_file: api/dotnet/.env
    ports:
      - 3000:80
      - 3001:433
    depends_on:
      - database
    networks:
      - dmft_network

####################### Networks Definition #######################
networks:
  dmft_network:
    driver: bridge

####################### Volumes Definition #######################
volumes:
  database-data: